# Generated by Django 4.2.1 on 2023-05-22 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pokemons", "0002_pokemon_created_at_pokemon_updated_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pokemonmove",
            name="power",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
