version: "3.9"

services:
  core:
    platform: linux/x86_64  # https://github.com/GrahamDumpleton/wrapt/issues/199#issuecomment-1054696160
    build:
      context: ../
      dockerfile: docker/Dockerfile
    volumes:
      - ../pokestar/:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
      - broker
      - worker
    env_file:
      - ./config/.env.core.local

  worker:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    volumes:
      - ../pokestar/:/code
    command: /bin/sh -c 'sleep 5 && su -m pokestar -c "celery -A pokestar.celery worker -l debug -E"'
    depends_on:
      - db
      - broker
    env_file:
      - ./config/.env.core.local

  db:
    image: postgres:12.8
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - ./config/.env.postgres.local

  broker:
    image: rabbitmq:3.11
    volumes:
      - ./data/broker/db:/var/lib/rabbitmq/
      - ./data/broker/config:/etc/rabbitmq/
    ports:
      - "5672:5672"
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=passW
