version: "3.9"

services:
  core:
    platform: linux/x86_64  # https://github.com/GrahamDumpleton/wrapt/issues/199#issuecomment-1054696160
    build:
      context: ../
      dockerfile: docker/Dockerfile
    volumes:
      - ../:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - ./config/.env.core.local

  db:
    image: postgres:12.8
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - ./config/.env.postgres.local
